language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - rust: nightly
      env: CARGO_TEST_FLAGS="--features bench"

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script: cargo test --verbose $CARGO_TEST_FLAGS

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
