[package]
name = "bvh"
description = "A fast BVH using SAH"
version = "0.0.0"
authors = [
    "Sven-Hendrik Haase <svenstaro@gmail.com>",
    "Alexander Dmitriev <alexander.dmitriev2580@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/svenstaro/bvh"
documentation = "https://docs.rs/crate/bvh"
keywords = ["bvh", "bounding", "volume", "sah", "aabb"]
license = "MIT"

[dependencies]
clippy = "0.0.91"
nalgebra = "0.10.1"

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
