[package]
name = "bsh"
description = "A fast BSH using SAH"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/mockersf/bvh"
documentation = "https://docs.rs/crate/bsh"
license = "MIT"

[dependencies]
glam = "0.21"
